name: Update Flight Data

# Controls when the workflow will run
on:
  schedule:
    # Runs the workflow every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow
  
jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the runner
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    # Install dependencies (if needed)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the webscraper script
    - name: Run Webscraper Script
      run: |
        python webscraper_departures.py

    # Commit and push the updated files to the repository
    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add seen_data_dep.txt departures_data.json
        git commit -m "Update flight data"
        git push
